# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('idTag', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('time', models.TimeField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('result', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
