# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='idTag',
            new_name='id_tag',
        ),
    ]
